spring.config.activate.on-profile=prod

spring.datasource.url=${POSTGRESQL_URL:jdbc:postgresql://localhost:5432/okr_db}
spring.datasource.username=${POSTGRESQL_USER:postgres}
spring.datasource.password=${POSTGRESQL_PASSWORD:Facil123}


spring.sql.init.mode=always
spring.flyway.clean-disabled=true

management.endpoint.health.show-details=never

logging.level.root=WARN
server.port=8080