spring.application.name=okr_back
# Define el perfil activo.
# Si existe la variable de entorno SPRING_PROFILES_ACTIVE, la usa.
# Si no, usa 'dev' por defecto.
spring.profiles.active=prod

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10

# JWT
# Se lee de la variable de entorno JWT_SECRET.
# En desarrollo, se puede definir en application-dev.properties o usar un valor por defecto seguro solo para dev.

